trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: api-automation-secrets

parameters:
  - name: RUN_LIVE_TESTS
    displayName: Run Live Contract Tests
    type: boolean
    default: false

jobs:
  - job: api_test
    displayName: 'API Tests'
    steps:
      - task: Maven@4
        displayName: 'Run Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean test'
          options: '-Denv=ci'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
        env:
          AUTH_USERNAME: $(AUTH_USERNAME)
          AUTH_PASSWORD: $(AUTH_PASSWORD)

  - job: live_contract_test
    displayName: 'Run Live Contract Tests'
    dependsOn: api_test
    condition: and(succeeded(), eq('${{ parameters.RUN_LIVE_TESTS }}', true))
    steps:
      - task: Maven@4
        displayName: 'Run Live Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          options: '-Dmode=live -Denv=live -Dgroups=live -DexcludedGroups='
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'


