trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RUN_LIVE_TESTS
    displayName: Run Live Contract Tests
    type: boolean
    default: false

jobs:
  - job: api_test
    displayName: 'API Tests'
    steps:
      - task: Maven@4
        displayName: 'Run Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean test'
          options: '-Denv=ci'
          publishJunitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
        env:
          AUTH_USERNAME: $(AUTH_USERNAME)
          AUTH_PASSWORD: $(AUTH_PASSWORD)

